language: python
sudo: required
dist: trusty

python:
  - "3.5"

install:
  - pip3 install -r requirements.txt
  - pip3 install codecov
  - ./utils/scripts/jumpscale_install.sh

script:
  - make test

after_success:
- codecov